kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: maven:3-jdk-11
    volumes:
      - name: mvn-cache
        path: /root/.m2
    commands:
      - mvn compile package -DskipTests=true -Dmaven.javadoc.skip=true -B -V

  - name: publish
    image: amd64/ubuntu:22.10
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
      - name: docker-command
        path: /usr/bin/docker
    commands:
      - docker build -t myz/wxapp-web:0.0.1-SNAPSHOT .

  - name: run
    image: amd64/ubuntu:22.10
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
      - name: docker-command
        path: /usr/bin/docker
    commands:
      - sh docker-run.sh myz wxapp-web 0.0.1-SNAPSHOT ${instance_id}

volumes:
  - name: mvn-cache
    host:
      path: /appdata/maven/cache

  - name: docker-sock
    host:
      path: /var/run/docker.sock

  - name: docker-command
    host:
      path: /usr/bin/docker