kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

trigger:
  event:

steps:
  - name: build
    commands:
      - mvn -U compile package -DskipTests=true -Dmaven.javadoc.skip=true -B -V

  - name: image
    commands:
      - docker --config /root/.docker build -t myz/wxapp-web:1.0 .

  - name: put-version
    commands:
      - sed "s/__LABEL_VERSION__/v${DRONE_BUILD_NUMBER}/g" wxapp-web-deploy.yaml > wxapp-web-deploy-version.yaml

  - name: deploy
    commands:
      - kubectl apply -f wxapp-web-deploy-version.yaml