kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: maven:3-jdk-11
    volumes:
      - name: mvn-cache
        path: /root/.m2
      - name: mvn-build
        path: /app/build
    commands:
      - mvn compile package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - cp target/wxapp-web-0.0.1-SNAPSHOT.jar /app/build/wxapp-web-0.0.1-SNAPSHOT.jar
      - cp Dockerfile /app/build/Dockerfile
      - cp docker-run.sh /app/build/docker-run.sh

  - name: start
    image: appleboy/drone-ssh # SSH工具镜像
    settings:
      host: 212.129.252.68 # 远程连接地址
      username: root # 远程连接账号
      port: 22 # 远程连接端口
      password:
        from_secret: ssh_password
      command_timeout: 5m # 远程执行命令超时时间
      script:
        - cd /app/build # 进入宿主机构建目录
        - chmod +x docker-run.sh # 更改为可执行脚本
        - ./docker-run.sh # 运行脚本打包应用镜像并运行

volumes:
  - name: mvn-build
    host:
      path: /appdata/maven/build

  - name: mvn-cache
    host:
      path: /appdata/maven/cache