apiVersion: apps/v1
kind: Deployment
metadata:
  name: wxapp-web-deployment
spec:
  selector:
    matchLabels:
      app: wxapp-web
  replicas: 1
  template:
    metadata:
      labels:
        app: wxapp-web
        version: __LABEL_VERSION__
    spec:
      containers:
        - name: wxapp-web
          image: myz/wxapp-web:1.0
          ports:
            - containerPort: 9190
              name: wxapp-web
          volumeMounts:
            - name: localtime-config
              mountPath: /etc/localtime
            - name: timezone-config
              mountPath: /etc/timezone
      volumes:
        - name: localtime-config
          #挂载主机localtime
          hostPath:
            path: /etc/localtime
        - name: timezone-config
          #挂载主机timezone
          hostPath:
            path: /etc/timezone
