book:
  default:
    author: zmy-dev
    name: windy-dev

server:
  port: 9090

database:
  common:
    validationQuery: SELECT 1

  dbuser:
    username: wxapp
    password: javGa2kFLbzQ_
    url: jdbc:mariadb://212.129.252.68:3306/wxapp
    driverClassName: org.mariadb.jdbc.Driver
    initialSize: 0
    maxTotal: 4
    maxIdle: 4
    minIdle: 0

  dbquartz:
    username: quartz
    password: 8drFUuACugak6A
    url: jdbc:mariadb://212.129.252.68:3306/quartz
    driverClassName: org.mariadb.jdbc.Driver
    initialSize: 0
    maxTotal: 4
    maxIdle: 4
    minIdle: 0
