book:
  default:
    author: zmy-test
    name: windy-test

server:
  port: 8000

database:
  common:
    validationQuery: SELECT 1

  dbuser:
    username: test
    password: test1019
    url: jdbc:mysql://bj-cdb-a1k9bmg8.sql.tencentcdb.com:61153/test
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 0
    maxTotal: 4
    maxIdle: 4
    minIdle: 0
